/**
 * MathBlitz Kingdom - Worlds and Curated 100 Level Configurations
 */

import { JourneyLevelDef, WorldDef, WorldId } from "./types";

export const WORLDS: WorldDef[] = [
  {
    id: "number_forest",
    worldNumber: 1,
    name: "Number Forest",
    subtitle: "Lush Realm of Fundamentals",
    theme: "Dense magical forest with glowing number stones, fireflies, and wooden bridges",
    levelsRange: [1, 20],
    bossLevel: 20,
    palette: {
      primary: "#10B981", // Emerald
      secondary: "#047857", // Deep Green
      accent: "#34D399", // Light Green
      backgroundTop: "#064E3B",
      backgroundBottom: "#022C22",
      pathColor: "#854D0E", // Wood brown
      pathBorder: "#FEF08A", // Amber glow
      nodeUnlocked: "#10B981",
      nodeLocked: "#374151",
      nodeBoss: "#F59E0B",
      ambientParticle: "#A7F3D0",
    },
    ambientType: "fireflies",
    boss: {
      name: "Forest Guardian",
      avatar: "🧙",
      title: "Keeper of Ancient Numerals",
      quote: "None traverse the Number Forest without mastering the fundamental laws!",
      introDialogue: "Welcome, challenger. Show me your swift mental calculation to earn the Forest Crown!",
      victoryDialogue: "Impeccable calculation! The path to Fraction Valley is now clear.",
      defeatDialogue: "Your numbers were too fast for my ancient spells!",
      colorScheme: {
        primary: "#10B981",
        secondary: "#047857",
        accent: "#FBBF24",
      },
    },
    unlockRequirements: {
      previousWorldBossCompleted: false, // World 1 is always unlocked
    },
  },
  {
    id: "fraction_valley",
    worldNumber: 2,
    name: "Fraction Valley",
    subtitle: "Mystical Cascades of Proportions",
    theme: "Mountain valley with waterfalls, purple crystals, and floating fraction stones",
    levelsRange: [21, 40],
    bossLevel: 40,
    palette: {
      primary: "#8B5CF6", // Purple
      secondary: "#6D28D9",
      accent: "#A78BFA",
      backgroundTop: "#4C1D95",
      backgroundBottom: "#2E1065",
      pathColor: "#4338CA",
      pathBorder: "#C084FC",
      nodeUnlocked: "#8B5CF6",
      nodeLocked: "#374151",
      nodeBoss: "#EC4899",
      ambientParticle: "#DDD6FE",
    },
    ambientType: "waterfall_crystals",
    boss: {
      name: "Fraction Overlord",
      avatar: "🧝‍♂️",
      title: "Master of Equal Parts",
      quote: "Can you simplify what cannot be broken?",
      introDialogue: "You dare cross the valley? Fractions will divide your courage!",
      victoryDialogue: "You have balanced every portion with sheer elegance.",
      defeatDialogue: "The parts... they have united against me!",
      colorScheme: {
        primary: "#8B5CF6",
        secondary: "#6D28D9",
        accent: "#F472B6",
      },
    },
    unlockRequirements: {
      previousWorldBossCompleted: true,
    },
  },
  {
    id: "percentage_city",
    worldNumber: 3,
    name: "Percentage City",
    subtitle: "Neon Metropolis of Commerce",
    theme: "Cyberpunk metropolis with neon signs, price boards, and digital billboards",
    levelsRange: [41, 60],
    bossLevel: 60,
    palette: {
      primary: "#06B6D4", // Cyan
      secondary: "#0891B2",
      accent: "#67E8F9",
      backgroundTop: "#164E63",
      backgroundBottom: "#082F49",
      pathColor: "#1E293B",
      pathBorder: "#38BDF8",
      nodeUnlocked: "#06B6D4",
      nodeLocked: "#374151",
      nodeBoss: "#F43F5E",
      ambientParticle: "#A5F3FC",
    },
    ambientType: "neon_glow",
    boss: {
      name: "Market Tycoon",
      avatar: "🤖",
      title: "Architect of 100 Percent",
      quote: "Profit and loss are merely equations in my city of percentages.",
      introDialogue: "Time is money, and rate is everything! Let us see if your discounts hold value.",
      victoryDialogue: "A hundred percent victory! You've cornered the market!",
      defeatDialogue: "My rate of growth has dropped to zero... you win!",
      colorScheme: {
        primary: "#06B6D4",
        secondary: "#0891B2",
        accent: "#FB7185",
      },
    },
    unlockRequirements: {
      previousWorldBossCompleted: true,
    },
  },
  {
    id: "algebra_mountain",
    worldNumber: 4,
    name: "Algebra Mountain",
    subtitle: "Highland of the Unknowns",
    theme: "Ancient golden mountain cliffs with floating variable runes and ancient ruins",
    levelsRange: [61, 80],
    bossLevel: 80,
    palette: {
      primary: "#F59E0B", // Amber
      secondary: "#D97706",
      accent: "#FCD34D",
      backgroundTop: "#78350F",
      backgroundBottom: "#451A03",
      pathColor: "#7C2D12",
      pathBorder: "#FDE68A",
      nodeUnlocked: "#F59E0B",
      nodeLocked: "#374151",
      nodeBoss: "#EF4444",
      ambientParticle: "#FEF3C7",
    },
    ambientType: "cloud_drift",
    boss: {
      name: "Equation Titan",
      avatar: "👹",
      title: "Guardian of Variable X",
      quote: "To know the unknown is to conquer the summit.",
      introDialogue: "Solve for X before the mountain collapses beneath you!",
      victoryDialogue: "You have solved every riddle the peak could muster.",
      defeatDialogue: "X has been found... the summit is yours!",
      colorScheme: {
        primary: "#F59E0B",
        secondary: "#D97706",
        accent: "#F87171",
      },
    },
    unlockRequirements: {
      previousWorldBossCompleted: true,
    },
  },
  {
    id: "geometry_castle",
    worldNumber: 5,
    name: "Geometry Castle",
    subtitle: "Citadel of Angles and Forms",
    theme: "Crimson and gold castle with rotating polygons, crystal gates, and perimeter halls",
    levelsRange: [81, 100],
    bossLevel: 100,
    palette: {
      primary: "#EF4444", // Crimson
      secondary: "#B91C1C",
      accent: "#FCA5A5",
      backgroundTop: "#7F1D1D",
      backgroundBottom: "#450A0A",
      pathColor: "#881337",
      pathBorder: "#FDE047",
      nodeUnlocked: "#EF4444",
      nodeLocked: "#374151",
      nodeBoss: "#8B5CF6",
      ambientParticle: "#FECACA",
    },
    ambientType: "floating_polygons",
    boss: {
      name: "Grand Architect",
      avatar: "👑",
      title: "Ruler of Mathematical Dimensions",
      quote: "Perfection is equilateral. Can you measure up to the ultimate throne?",
      introDialogue: "Enter the Grand Geometry Sanctum! Prove your mastery of all angles!",
      victoryDialogue: "Magnificent! You have conquered the five realms of MathBlitz Kingdom!",
      defeatDialogue: "All symmetry bows to your mathematical supremacy!",
      colorScheme: {
        primary: "#EF4444",
        secondary: "#B91C1C",
        accent: "#A78BFA",
      },
    },
    unlockRequirements: {
      previousWorldBossCompleted: true,
    },
  },
];

// Helper to determine star threshold
const standardThresholds = (accuracy = 0.8, maxTime = 50) => ({
  twoStarMinAccuracy: accuracy,
  threeStarMinAccuracy: 1.0,
  threeStarMaxTimeSeconds: maxTime,
});

// Curated 100 Level Definitions
export const CURATED_LEVELS: JourneyLevelDef[] = [
  // ── WORLD 1: NUMBER FOREST (Levels 1–20) ──────────────────────────────────
  {
    id: 1,
    worldId: "number_forest",
    levelNumber: 1,
    title: "Number Explorer",
    levelType: "normal",
    concepts: ["number_comparison", "number_ordering"],
    difficulty: 1,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.75, 22),
    rewardXp: 50,
    rewardTokens: 5,
    description: "Compare small numbers and find which is greater or smaller.",
  },
  {
    id: 2,
    worldId: "number_forest",
    levelNumber: 2,
    title: "Bigger or Smaller",
    levelType: "normal",
    concepts: ["number_comparison"],
    difficulty: 1,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.75, 22),
    rewardXp: 50,
    rewardTokens: 5,
    description: "Spot the greater and smaller two-digit numbers.",
  },
  {
    id: 3,
    worldId: "number_forest",
    levelNumber: 3,
    title: "Number Order",
    levelType: "normal",
    concepts: ["number_ordering"],
    difficulty: 1,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.75, 22),
    rewardXp: 60,
    rewardTokens: 5,
    description: "Arrange numbers from smallest to largest.",
  },
  {
    id: 4,
    worldId: "number_forest",
    levelNumber: 4,
    title: "Missing Number",
    levelType: "normal",
    concepts: ["missing_number"],
    difficulty: 1,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.75, 22),
    rewardXp: 60,
    rewardTokens: 5,
    description: "Find the missing number in clean addition sentences.",
  },
  {
    id: 5,
    worldId: "number_forest",
    levelNumber: 5,
    title: "Number Pattern",
    levelType: "puzzle",
    concepts: ["number_pattern"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 75,
    rewardTokens: 10,
    description: "Discover simple counting step patterns.",
  },
  {
    id: 6,
    worldId: "number_forest",
    levelNumber: 6,
    title: "Addition Trail",
    levelType: "normal",
    concepts: ["mental_addition"],
    difficulty: 1,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 70,
    rewardTokens: 5,
    description: "Add two-digit mental friendly numbers along the path.",
  },
  {
    id: 7,
    worldId: "number_forest",
    levelNumber: 7,
    title: "Quick Addition",
    levelType: "speed",
    concepts: ["mental_addition"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 80,
    rewardTokens: 8,
    description: "Fast-paced single and double digit additions.",
  },
  {
    id: 8,
    worldId: "number_forest",
    levelNumber: 8,
    title: "Addition Mix",
    levelType: "mixed",
    concepts: ["mental_addition", "missing_number"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 80,
    rewardTokens: 8,
    description: "Varied addition equations and sums.",
  },
  {
    id: 9,
    worldId: "number_forest",
    levelNumber: 9,
    title: "Subtraction Trail",
    levelType: "normal",
    concepts: ["mental_subtraction"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 80,
    rewardTokens: 5,
    description: "Clean mental subtractions with friendly regrouping.",
  },
  {
    id: 10,
    worldId: "number_forest",
    levelNumber: 10,
    title: "Quick Subtraction",
    levelType: "speed",
    concepts: ["mental_subtraction"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 90,
    rewardTokens: 10,
    description: "Speed subtraction round.",
  },
  {
    id: 11,
    worldId: "number_forest",
    levelNumber: 11,
    title: "Multiplication Basics",
    levelType: "normal",
    concepts: ["mental_multiplication"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 90,
    rewardTokens: 5,
    description: "Multiplication facts for tables 2 through 9.",
  },
  {
    id: 12,
    worldId: "number_forest",
    levelNumber: 12,
    title: "Multiplication Mix",
    levelType: "mixed",
    concepts: ["mental_multiplication"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 100,
    rewardTokens: 8,
    description: "Times table mastery under slight time pressure.",
  },
  {
    id: 13,
    worldId: "number_forest",
    levelNumber: 13,
    title: "Division Basics",
    levelType: "normal",
    concepts: ["mental_division"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 90,
    rewardTokens: 5,
    description: "Clean whole number divisions with zero remainders.",
  },
  {
    id: 14,
    worldId: "number_forest",
    levelNumber: 14,
    title: "Division Mix",
    levelType: "mixed",
    concepts: ["mental_division"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 100,
    rewardTokens: 8,
    description: "Fact family divisions and missing divisors.",
  },
  {
    id: 15,
    worldId: "number_forest",
    levelNumber: 15,
    title: "Mixed Arithmetic",
    levelType: "mixed",
    concepts: ["mental_addition", "mental_subtraction", "mental_multiplication", "mental_division"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 110,
    rewardTokens: 10,
    description: "All 4 basic operations combined.",
  },
  {
    id: 16,
    worldId: "number_forest",
    levelNumber: 16,
    title: "Mental Math Sprint",
    levelType: "speed_gate",
    concepts: ["mental_addition", "mental_subtraction", "mental_multiplication"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 125,
    rewardTokens: 15,
    description: "Speed Gate Challenge! Solve fast to unlock the forest trial.",
    speedGateId: "blitz_forest_sprint",
  },
  {
    id: 17,
    worldId: "number_forest",
    levelNumber: 17,
    title: "Number Logic",
    levelType: "puzzle",
    concepts: ["number_logic"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.75, 22),
    rewardXp: 120,
    rewardTokens: 10,
    description: "Riddles: 'I am greater than 20, less than 40, and divisible by 6.'",
  },
  {
    id: 18,
    worldId: "number_forest",
    levelNumber: 18,
    title: "Arithmetic Puzzle",
    levelType: "puzzle",
    concepts: ["number_logic", "missing_number"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 130,
    rewardTokens: 10,
    description: "Deduction puzzles using operations and clues.",
  },
  {
    id: 19,
    worldId: "number_forest",
    levelNumber: 19,
    title: "Forest Trial",
    levelType: "gauntlet",
    concepts: ["mental_addition", "mental_subtraction", "mental_multiplication", "mental_division", "number_logic"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 150,
    rewardTokens: 15,
    description: "Final gauntlet before facing the Forest Guardian.",
  },
  {
    id: 20,
    worldId: "number_forest",
    levelNumber: 20,
    title: "Forest Guardian Boss",
    levelType: "boss",
    concepts: ["mental_addition", "mental_subtraction", "mental_multiplication", "mental_division", "number_logic"],
    difficulty: 5,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 300,
    rewardTokens: 50,
    isMilestone: true,
    description: "Defeat the Forest Guardian to unlock World 2: Fraction Valley!",
    boss: WORLDS[0].boss,
  },

  // ── WORLD 2: FRACTION VALLEY (Levels 21–40) ───────────────────────────────
  {
    id: 21,
    worldId: "fraction_valley",
    levelNumber: 1,
    title: "Fraction Explorer",
    levelType: "normal",
    concepts: ["fraction_recognition"],
    difficulty: 1,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.75, 22),
    rewardXp: 70,
    rewardTokens: 5,
    description: "Identify halves, thirds, and quarters.",
  },
  {
    id: 22,
    worldId: "fraction_valley",
    levelNumber: 2,
    title: "Half or Whole",
    levelType: "normal",
    concepts: ["fraction_recognition"],
    difficulty: 1,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 70,
    rewardTokens: 5,
    description: "Compare fractions against 1/2 and 1.",
  },
  {
    id: 23,
    worldId: "fraction_valley",
    levelNumber: 3,
    title: "Fraction Recognition",
    levelType: "normal",
    concepts: ["fraction_recognition"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 80,
    rewardTokens: 5,
    description: "Match visual fraction portions to numbers.",
  },
  {
    id: 24,
    worldId: "fraction_valley",
    levelNumber: 4,
    title: "Compare Fractions",
    levelType: "normal",
    concepts: ["fraction_comparison"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 85,
    rewardTokens: 5,
    description: "Which fraction is larger: same numerator or same denominator?",
  },
  {
    id: 25,
    worldId: "fraction_valley",
    levelNumber: 5,
    title: "Fraction Number Line",
    levelType: "puzzle",
    concepts: ["fraction_comparison"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 90,
    rewardTokens: 10,
    description: "Place fractions between 0 and 1 on a mental number line.",
  },
  {
    id: 26,
    worldId: "fraction_valley",
    levelNumber: 6,
    title: "Equivalent Fractions",
    levelType: "normal",
    concepts: ["equivalent_fractions"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 95,
    rewardTokens: 5,
    description: "Recognize equivalent values (e.g. 2/4 = 1/2, 3/6 = 1/2).",
  },
  {
    id: 27,
    worldId: "fraction_valley",
    levelNumber: 7,
    title: "Simplify Fractions",
    levelType: "normal",
    concepts: ["simplify_fractions"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 100,
    rewardTokens: 8,
    description: "Reduce friendly fractions to simplest form.",
  },
  {
    id: 28,
    worldId: "fraction_valley",
    levelNumber: 8,
    title: "Fraction Match",
    levelType: "mixed",
    concepts: ["equivalent_fractions", "simplify_fractions"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 100,
    rewardTokens: 8,
    description: "Find matching equivalent and simplified pairs.",
  },
  {
    id: 29,
    worldId: "fraction_valley",
    levelNumber: 9,
    title: "Fraction Logic",
    levelType: "puzzle",
    concepts: ["fraction_comparison", "fraction_reasoning"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 110,
    rewardTokens: 10,
    description: "Logical deduction with fraction portions.",
  },
  {
    id: 30,
    worldId: "fraction_valley",
    levelNumber: 10,
    title: "Fraction Sprint",
    levelType: "speed_gate",
    concepts: ["fraction_comparison", "simplify_fractions"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 125,
    rewardTokens: 15,
    description: "Speed Gate! Rapid fraction equivalence recognition.",
    speedGateId: "blitz_fraction_sprint",
  },
  {
    id: 31,
    worldId: "fraction_valley",
    levelNumber: 11,
    title: "Add Simple Fractions",
    levelType: "normal",
    concepts: ["fraction_arithmetic"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 115,
    rewardTokens: 8,
    description: "Add fractions with like denominators (e.g. 1/5 + 2/5).",
  },
  {
    id: 32,
    worldId: "fraction_valley",
    levelNumber: 12,
    title: "Subtract Simple Fractions",
    levelType: "normal",
    concepts: ["fraction_arithmetic"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 115,
    rewardTokens: 8,
    description: "Subtract fractions with like denominators.",
  },
  {
    id: 33,
    worldId: "fraction_valley",
    levelNumber: 13,
    title: "Fraction Mix",
    levelType: "mixed",
    concepts: ["fraction_arithmetic", "equivalent_fractions"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 120,
    rewardTokens: 8,
    description: "Mixed addition, subtraction, and simplification.",
  },
  {
    id: 34,
    worldId: "fraction_valley",
    levelNumber: 14,
    title: "Fraction Reasoning",
    levelType: "puzzle",
    concepts: ["fraction_reasoning"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 130,
    rewardTokens: 10,
    description: "Mental fraction word scenarios (e.g., half of 60, 3/4 of 40).",
  },
  {
    id: 35,
    worldId: "fraction_valley",
    levelNumber: 15,
    title: "Fraction Challenge",
    levelType: "normal",
    concepts: ["fraction_arithmetic", "fraction_reasoning"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 135,
    rewardTokens: 10,
    description: "Combining fraction parts and whole number fractions.",
  },
  {
    id: 36,
    worldId: "fraction_valley",
    levelNumber: 16,
    title: "Mental Fraction Challenge",
    levelType: "speed",
    concepts: ["fraction_arithmetic", "simplify_fractions"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 140,
    rewardTokens: 12,
    description: "Timed fraction calculations.",
  },
  {
    id: 37,
    worldId: "fraction_valley",
    levelNumber: 17,
    title: "Fraction Puzzle",
    levelType: "puzzle",
    concepts: ["fraction_reasoning", "number_logic"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.75, 22),
    rewardXp: 150,
    rewardTokens: 12,
    description: "Find unknown fractions given logical constraints.",
  },
  {
    id: 38,
    worldId: "fraction_valley",
    levelNumber: 18,
    title: "Valley Trial",
    levelType: "gauntlet",
    concepts: ["equivalent_fractions", "fraction_arithmetic", "fraction_reasoning"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 160,
    rewardTokens: 15,
    description: "Comprehensive valley trial before the gate.",
  },
  {
    id: 39,
    worldId: "fraction_valley",
    levelNumber: 19,
    title: "Valley Gauntlet",
    levelType: "gauntlet",
    concepts: ["equivalent_fractions", "fraction_arithmetic", "fraction_reasoning"],
    difficulty: 5,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 180,
    rewardTokens: 15,
    description: "Intense fraction obstacle course before the Overlord.",
  },
  {
    id: 40,
    worldId: "fraction_valley",
    levelNumber: 20,
    title: "Fraction Overlord Boss",
    levelType: "boss",
    concepts: ["equivalent_fractions", "fraction_arithmetic", "fraction_reasoning", "fraction_comparison"],
    difficulty: 5,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 350,
    rewardTokens: 60,
    isMilestone: true,
    description: "Defeat the Fraction Overlord to unlock World 3: Percentage City!",
    boss: WORLDS[1].boss,
  },

  // ── WORLD 3: PERCENTAGE CITY (Levels 41–60) ───────────────────────────────
  {
    id: 41,
    worldId: "percentage_city",
    levelNumber: 1,
    title: "Percentage Explorer",
    levelType: "normal",
    concepts: ["percentage_basics"],
    difficulty: 1,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.75, 22),
    rewardXp: 90,
    rewardTokens: 5,
    description: "Understand % out of 100.",
  },
  {
    id: 42,
    worldId: "percentage_city",
    levelNumber: 2,
    title: "Percentage Basics",
    levelType: "normal",
    concepts: ["percentage_basics"],
    difficulty: 1,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 90,
    rewardTokens: 5,
    description: "Find 50% and 100% of friendly round numbers.",
  },
  {
    id: 43,
    worldId: "percentage_city",
    levelNumber: 3,
    title: "Find 10%",
    levelType: "normal",
    concepts: ["percentage_of_number"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 100,
    rewardTokens: 5,
    description: "Mental trick: drop zero or move decimal point one place left.",
  },
  {
    id: 44,
    worldId: "percentage_city",
    levelNumber: 4,
    title: "Find 5%",
    levelType: "normal",
    concepts: ["percentage_of_number"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 105,
    rewardTokens: 5,
    description: "Find 10% then take half.",
  },
  {
    id: 45,
    worldId: "percentage_city",
    levelNumber: 5,
    title: "Find 25%",
    levelType: "normal",
    concepts: ["percentage_of_number"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 110,
    rewardTokens: 10,
    description: "Mental trick: find one quarter (divide by 4 or halve twice).",
  },
  {
    id: 46,
    worldId: "percentage_city",
    levelNumber: 6,
    title: "Percentage ↔ Decimal",
    levelType: "normal",
    concepts: ["percentage_conversion"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 115,
    rewardTokens: 5,
    description: "Convert 25% = 0.25, 50% = 0.5, 10% = 0.1.",
  },
  {
    id: 47,
    worldId: "percentage_city",
    levelNumber: 7,
    title: "Percentage ↔ Fraction",
    levelType: "normal",
    concepts: ["percentage_conversion"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 115,
    rewardTokens: 5,
    description: "Convert 50% = 1/2, 25% = 1/4, 20% = 1/5.",
  },
  {
    id: 48,
    worldId: "percentage_city",
    levelNumber: 8,
    title: "Percentage Match",
    levelType: "mixed",
    concepts: ["percentage_conversion"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 120,
    rewardTokens: 8,
    description: "Match percentages, fractions, and decimals.",
  },
  {
    id: 49,
    worldId: "percentage_city",
    levelNumber: 9,
    title: "Percentage Logic",
    levelType: "puzzle",
    concepts: ["percentage_of_number", "number_logic"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 130,
    rewardTokens: 10,
    description: "Logic reasoning with percentages.",
  },
  {
    id: 50,
    worldId: "percentage_city",
    levelNumber: 10,
    title: "Percentage Sprint",
    levelType: "speed_gate",
    concepts: ["percentage_of_number"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 140,
    rewardTokens: 15,
    description: "Speed Gate! Rapid 10%, 25%, and 50% calculations.",
    speedGateId: "blitz_percentage_sprint",
  },
  {
    id: 51,
    worldId: "percentage_city",
    levelNumber: 11,
    title: "Simple Percentage of Number",
    levelType: "normal",
    concepts: ["percentage_of_number"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 130,
    rewardTokens: 8,
    description: "Calculate 20% of 150, 75% of 80.",
  },
  {
    id: 52,
    worldId: "percentage_city",
    levelNumber: 12,
    title: "Discounts",
    levelType: "normal",
    concepts: ["discounts_shopping"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 140,
    rewardTokens: 8,
    description: "Find discounted prices ($100 item with 20% off = $80).",
  },
  {
    id: 53,
    worldId: "percentage_city",
    levelNumber: 13,
    title: "Price Changes",
    levelType: "mixed",
    concepts: ["discounts_shopping", "percentage_change"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 140,
    rewardTokens: 8,
    description: "Shopping scenarios with markups and sales.",
  },
  {
    id: 54,
    worldId: "percentage_city",
    levelNumber: 14,
    title: "Percentage Increase",
    levelType: "normal",
    concepts: ["percentage_change"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 150,
    rewardTokens: 10,
    description: "Increase $50 by 10%, 20%, or 50%.",
  },
  {
    id: 55,
    worldId: "percentage_city",
    levelNumber: 15,
    title: "Percentage Decrease",
    levelType: "normal",
    concepts: ["percentage_change"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 150,
    rewardTokens: 10,
    description: "Decrease clean amounts by 10%, 25%, or 50%.",
  },
  {
    id: 56,
    worldId: "percentage_city",
    levelNumber: 16,
    title: "Mental Percentage Challenge",
    levelType: "speed",
    concepts: ["percentage_of_number", "discounts_shopping"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 160,
    rewardTokens: 12,
    description: "High speed retail mathematics.",
  },
  {
    id: 57,
    worldId: "percentage_city",
    levelNumber: 17,
    title: "Shopping Math",
    levelType: "puzzle",
    concepts: ["discounts_shopping", "percentage_change"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.75, 22),
    rewardXp: 170,
    rewardTokens: 12,
    description: "Best deal comparison and multi-item percentages.",
  },
  {
    id: 58,
    worldId: "percentage_city",
    levelNumber: 18,
    title: "City Puzzle",
    levelType: "puzzle",
    concepts: ["percentage_of_number", "number_logic"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 175,
    rewardTokens: 15,
    description: "Decipher city percentage billboards.",
  },
  {
    id: 59,
    worldId: "percentage_city",
    levelNumber: 19,
    title: "Percentage Gauntlet",
    levelType: "gauntlet",
    concepts: ["percentage_of_number", "percentage_conversion", "discounts_shopping", "percentage_change"],
    difficulty: 5,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 190,
    rewardTokens: 15,
    description: "Final gauntlet before facing the Market Tycoon.",
  },
  {
    id: 60,
    worldId: "percentage_city",
    levelNumber: 20,
    title: "Market Tycoon Boss",
    levelType: "boss",
    concepts: ["percentage_of_number", "discounts_shopping", "percentage_change", "percentage_conversion"],
    difficulty: 5,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 400,
    rewardTokens: 75,
    isMilestone: true,
    description: "Defeat the Market Tycoon to unlock World 4: Algebra Mountain!",
    boss: WORLDS[2].boss,
  },

  // ── WORLD 4: ALGEBRA MOUNTAIN (Levels 61–80) ──────────────────────────────
  {
    id: 61,
    worldId: "algebra_mountain",
    levelNumber: 1,
    title: "Algebra Explorer",
    levelType: "normal",
    concepts: ["simple_equation"],
    difficulty: 1,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.75, 22),
    rewardXp: 110,
    rewardTokens: 5,
    description: "Solve for the box/unknown: ? + 5 = 12.",
  },
  {
    id: 62,
    worldId: "algebra_mountain",
    levelNumber: 2,
    title: "Find X",
    levelType: "normal",
    concepts: ["simple_equation"],
    difficulty: 1,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 110,
    rewardTokens: 5,
    description: "Find X in x + 7 = 15 or x - 4 = 10.",
  },
  {
    id: 63,
    worldId: "algebra_mountain",
    levelNumber: 3,
    title: "Missing Number",
    levelType: "normal",
    concepts: ["simple_equation"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 120,
    rewardTokens: 5,
    description: "Equations with unknowns on either side.",
  },
  {
    id: 64,
    worldId: "algebra_mountain",
    levelNumber: 4,
    title: "Simple Equations",
    levelType: "normal",
    concepts: ["simple_equation"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 125,
    rewardTokens: 5,
    description: "Single step multiplication: 3x = 24, 5y = 35.",
  },
  {
    id: 65,
    worldId: "algebra_mountain",
    levelNumber: 5,
    title: "Equation Match",
    levelType: "puzzle",
    concepts: ["simple_equation"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 130,
    rewardTokens: 10,
    description: "Match equations having the exact same solution.",
  },
  {
    id: 66,
    worldId: "algebra_mountain",
    levelNumber: 6,
    title: "One-Step Equations",
    levelType: "normal",
    concepts: ["simple_equation"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 135,
    rewardTokens: 5,
    description: "Solve x / 4 = 6 or 9 + x = 25.",
  },
  {
    id: 67,
    worldId: "algebra_mountain",
    levelNumber: 7,
    title: "Two-Step Mental Equations",
    levelType: "normal",
    concepts: ["two_step_mental_equation"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 140,
    rewardTokens: 8,
    description: "Solve 2x + 3 = 11, 3x - 2 = 13 mentally.",
  },
  {
    id: 68,
    worldId: "algebra_mountain",
    levelNumber: 8,
    title: "Number Patterns",
    levelType: "puzzle",
    concepts: ["number_pattern"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 145,
    rewardTokens: 8,
    description: "Algebraic sequence rules (e.g. nth term = 2n + 1).",
  },
  {
    id: 69,
    worldId: "algebra_mountain",
    levelNumber: 9,
    title: "Algebra Logic",
    levelType: "puzzle",
    concepts: ["algebra_puzzle"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 150,
    rewardTokens: 10,
    description: "System of 2 simple friendly equations (a + b = 10, a - b = 2).",
  },
  {
    id: 70,
    worldId: "algebra_mountain",
    levelNumber: 10,
    title: "Algebra Sprint",
    levelType: "speed_gate",
    concepts: ["simple_equation"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 160,
    rewardTokens: 15,
    description: "Speed Gate! Rapid one-step algebraic deductions.",
    speedGateId: "blitz_algebra_sprint",
  },
  {
    id: 71,
    worldId: "algebra_mountain",
    levelNumber: 11,
    title: "Equation Mix",
    levelType: "mixed",
    concepts: ["simple_equation", "two_step_mental_equation"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 155,
    rewardTokens: 8,
    description: "Blend of 1-step and 2-step mental equations.",
  },
  {
    id: 72,
    worldId: "algebra_mountain",
    levelNumber: 12,
    title: "Mental Algebra",
    levelType: "normal",
    concepts: ["two_step_mental_equation"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 160,
    rewardTokens: 8,
    description: "Quick mental balance methods.",
  },
  {
    id: 73,
    worldId: "algebra_mountain",
    levelNumber: 13,
    title: "Variable Puzzle",
    levelType: "puzzle",
    concepts: ["algebra_puzzle"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 170,
    rewardTokens: 10,
    description: "Shape algebra: ⭐ + 🔷 = 12, 2⭐ = 16. Find 🔷.",
  },
  {
    id: 74,
    worldId: "algebra_mountain",
    levelNumber: 14,
    title: "Equation Challenge",
    levelType: "normal",
    concepts: ["two_step_mental_equation"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 175,
    rewardTokens: 10,
    description: "Solve 4x + 7 = 31, 5x - 4 = 26.",
  },
  {
    id: 75,
    worldId: "algebra_mountain",
    levelNumber: 15,
    title: "Mountain Trial",
    levelType: "gauntlet",
    concepts: ["simple_equation", "two_step_mental_equation", "algebra_puzzle"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 180,
    rewardTokens: 12,
    description: "High altitude algebraic ascent.",
  },
  {
    id: 76,
    worldId: "algebra_mountain",
    levelNumber: 16,
    title: "Algebra Reasoning",
    levelType: "puzzle",
    concepts: ["algebra_puzzle"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.75, 22),
    rewardXp: 185,
    rewardTokens: 12,
    description: "Deductive number relationships.",
  },
  {
    id: 77,
    worldId: "algebra_mountain",
    levelNumber: 17,
    title: "Algebra Puzzle",
    levelType: "puzzle",
    concepts: ["algebra_puzzle", "two_step_mental_equation"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 190,
    rewardTokens: 12,
    description: "Complex balance scale logic.",
  },
  {
    id: 78,
    worldId: "algebra_mountain",
    levelNumber: 18,
    title: "Mountain Gauntlet",
    levelType: "gauntlet",
    concepts: ["simple_equation", "two_step_mental_equation", "algebra_puzzle"],
    difficulty: 5,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 200,
    rewardTokens: 15,
    description: "Cliffside trials before the summit titan.",
  },
  {
    id: 79,
    worldId: "algebra_mountain",
    levelNumber: 19,
    title: "Final Climb",
    levelType: "speed",
    concepts: ["two_step_mental_equation"],
    difficulty: 5,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 210,
    rewardTokens: 15,
    description: "Last push to the summit shrine.",
  },
  {
    id: 80,
    worldId: "algebra_mountain",
    levelNumber: 20,
    title: "Equation Titan Boss",
    levelType: "boss",
    concepts: ["simple_equation", "two_step_mental_equation", "algebra_puzzle"],
    difficulty: 5,
    questionCount: 5,
    timeLimitSeconds: 40,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 450,
    rewardTokens: 80,
    isMilestone: true,
    description: "Defeat the Equation Titan to unlock World 5: Geometry Castle!",
    boss: WORLDS[3].boss,
  },

  // ── WORLD 5: GEOMETRY CASTLE (Levels 81–100) ──────────────────────────────
  {
    id: 81,
    worldId: "geometry_castle",
    levelNumber: 1,
    title: "Shape Explorer",
    levelType: "normal",
    concepts: ["shape_recognition"],
    difficulty: 1,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.75, 22),
    rewardXp: 130,
    rewardTokens: 5,
    description: "Recognize polygons: triangle, square, pentagon, hexagon, octagon.",
  },
  {
    id: 82,
    worldId: "geometry_castle",
    levelNumber: 2,
    title: "Shape Recognition",
    levelType: "normal",
    concepts: ["shape_recognition"],
    difficulty: 1,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 130,
    rewardTokens: 5,
    description: "Number of sides, vertices, and parallel edges.",
  },
  {
    id: 83,
    worldId: "geometry_castle",
    levelNumber: 3,
    title: "Angles",
    levelType: "normal",
    concepts: ["angle_comparison"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 140,
    rewardTokens: 5,
    description: "Acute (<90°), Right (90°), Obtuse (>90°), Straight (180°).",
  },
  {
    id: 84,
    worldId: "geometry_castle",
    levelNumber: 4,
    title: "Angle Comparison",
    levelType: "normal",
    concepts: ["angle_comparison"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 145,
    rewardTokens: 5,
    description: "Compare angle sizes and identify complementary/supplementary pairs.",
  },
  {
    id: 85,
    worldId: "geometry_castle",
    levelNumber: 5,
    title: "Geometry Logic",
    levelType: "puzzle",
    concepts: ["geometry_logic"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 150,
    rewardTokens: 10,
    description: "Properties of regular vs irregular shapes.",
  },
  {
    id: 86,
    worldId: "geometry_castle",
    levelNumber: 6,
    title: "Perimeter Basics",
    levelType: "normal",
    concepts: ["mental_perimeter"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 155,
    rewardTokens: 5,
    description: "Perimeter of square ($4s$) and rectangle ($2(l + w)$).",
  },
  {
    id: 87,
    worldId: "geometry_castle",
    levelNumber: 7,
    title: "Mental Perimeter",
    levelType: "normal",
    concepts: ["mental_perimeter"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 160,
    rewardTokens: 8,
    description: "Calculate perimeters with missing side lengths.",
  },
  {
    id: 88,
    worldId: "geometry_castle",
    levelNumber: 8,
    title: "Area Basics",
    levelType: "normal",
    concepts: ["mental_area"],
    difficulty: 2,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 160,
    rewardTokens: 8,
    description: "Area of square ($s^2$) and rectangle ($l \\times w$).",
  },
  {
    id: 89,
    worldId: "geometry_castle",
    levelNumber: 9,
    title: "Mental Area",
    levelType: "normal",
    concepts: ["mental_area"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 170,
    rewardTokens: 8,
    description: "Area of right triangles ($\\frac{1}{2} b \\times h$) with friendly numbers.",
  },
  {
    id: 90,
    worldId: "geometry_castle",
    levelNumber: 10,
    title: "Geometry Sprint",
    levelType: "speed_gate",
    concepts: ["mental_perimeter", "mental_area", "shape_recognition"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 180,
    rewardTokens: 15,
    description: "Speed Gate! Rapid area, perimeter, and shape recognition.",
    speedGateId: "blitz_geometry_sprint",
  },
  {
    id: 91,
    worldId: "geometry_castle",
    levelNumber: 11,
    title: "Shape Puzzle",
    levelType: "puzzle",
    concepts: ["geometry_logic", "shape_recognition"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 175,
    rewardTokens: 10,
    description: "Composite shapes made of simple squares and rectangles.",
  },
  {
    id: 92,
    worldId: "geometry_castle",
    levelNumber: 12,
    title: "Angle Challenge",
    levelType: "normal",
    concepts: ["angle_comparison"],
    difficulty: 3,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 180,
    rewardTokens: 8,
    description: "Angles in a triangle sum to 180°.",
  },
  {
    id: 93,
    worldId: "geometry_castle",
    levelNumber: 13,
    title: "Geometry Mix",
    levelType: "mixed",
    concepts: ["mental_perimeter", "mental_area", "angle_comparison"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 190,
    rewardTokens: 10,
    description: "Blend of angles, perimeter, and area.",
  },
  {
    id: 94,
    worldId: "geometry_castle",
    levelNumber: 14,
    title: "Geometry Reasoning",
    levelType: "puzzle",
    concepts: ["geometry_logic"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.75, 22),
    rewardXp: 195,
    rewardTokens: 10,
    description: "Compare areas: which enclosure holds more space?",
  },
  {
    id: 95,
    worldId: "geometry_castle",
    levelNumber: 15,
    title: "Castle Trial",
    levelType: "gauntlet",
    concepts: ["mental_perimeter", "mental_area", "angle_comparison", "geometry_logic"],
    difficulty: 4,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 200,
    rewardTokens: 12,
    description: "Courtyard geometry trial.",
  },
  {
    id: 96,
    worldId: "geometry_castle",
    levelNumber: 16,
    title: "Geometry Gauntlet",
    levelType: "gauntlet",
    concepts: ["mental_perimeter", "mental_area", "angle_comparison"],
    difficulty: 5,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 210,
    rewardTokens: 15,
    description: "Traverse the hall of polygonal traps.",
  },
  {
    id: 97,
    worldId: "geometry_castle",
    levelNumber: 17,
    title: "Mental Geometry",
    levelType: "speed",
    concepts: ["mental_area", "mental_perimeter"],
    difficulty: 5,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 220,
    rewardTokens: 15,
    description: "Fast perimeter and area mental shortcuts.",
  },
  {
    id: 98,
    worldId: "geometry_castle",
    levelNumber: 18,
    title: "Final Gate",
    levelType: "puzzle",
    concepts: ["geometry_logic", "angle_comparison"],
    difficulty: 5,
    questionCount: 5,
    timeLimitSeconds: 30,
    starThresholds: standardThresholds(0.8, 22),
    rewardXp: 230,
    rewardTokens: 15,
    description: "Unlock the Golden Sanctum Gate with shape symmetry.",
  },
  {
    id: 99,
    worldId: "geometry_castle",
    levelNumber: 19,
    title: "Castle Challenge",
    levelType: "gauntlet",
    concepts: ["mental_perimeter", "mental_area", "angle_comparison", "shape_recognition", "geometry_logic"],
    difficulty: 5,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 250,
    rewardTokens: 20,
    description: "Penultimate trial before the Grand Architect's throne room.",
  },
  {
    id: 100,
    worldId: "geometry_castle",
    levelNumber: 20,
    title: "Grand Architect Boss",
    levelType: "boss",
    concepts: ["mental_perimeter", "mental_area", "angle_comparison", "shape_recognition", "geometry_logic"],
    difficulty: 5,
    questionCount: 5,
    timeLimitSeconds: 35,
    starThresholds: standardThresholds(0.85, 22),
    rewardXp: 500,
    rewardTokens: 100,
    isMilestone: true,
    description: "Defeat the Grand Architect to master the Five Realms of MathBlitz Kingdom!",
    boss: WORLDS[4].boss,
  },
];

// Helper functions for infinite journey extensibility
export function getWorldForLevel(levelId: number): WorldDef {
  const worldIndex = Math.floor((levelId - 1) / 20);
  if (worldIndex < WORLDS.length) {
    return WORLDS[worldIndex];
  }
  // Procedural infinite world definition for World 6+
  const worldNum = worldIndex + 1;
  const startLevel = (worldNum - 1) * 20 + 1;
  const endLevel = worldNum * 20;
  return {
    id: `world_${worldNum}`,
    worldNumber: worldNum,
    name: `Cosmic Realm ${worldNum}`,
    subtitle: `Infinite Mathematical Horizon`,
    theme: `Infinite stars, rotating celestial equations, and hyperdimensional paths`,
    levelsRange: [startLevel, endLevel],
    bossLevel: endLevel,
    palette: {
      primary: "#6366F1",
      secondary: "#4338CA",
      accent: "#818CF8",
      backgroundTop: "#1E1B4B",
      backgroundBottom: "#0F172A",
      pathColor: "#312E81",
      pathBorder: "#C7D2FE",
      nodeUnlocked: "#6366F1",
      nodeLocked: "#374151",
      nodeBoss: "#EC4899",
      ambientParticle: "#E0E7FF",
    },
    ambientType: "floating_polygons",
    boss: {
      name: `Cosmic Guardian ${worldNum}`,
      avatar: "🌌",
      title: "Master of Infinity",
      quote: "Numbers never end, and neither does your quest.",
      introDialogue: "Welcome to the outer cosmos of mathematics!",
      victoryDialogue: "A glorious ascension across the infinite cosmos!",
      defeatDialogue: "You have transcended another horizon!",
      colorScheme: {
        primary: "#6366F1",
        secondary: "#4338CA",
        accent: "#F472B6",
      },
    },
    unlockRequirements: {
      previousWorldBossCompleted: true,
    },
  };
}

export function getLevelDef(levelId: number): JourneyLevelDef {
  if (levelId <= CURATED_LEVELS.length) {
    return CURATED_LEVELS[levelId - 1];
  }
  // Procedural level definition for levels beyond 100
  const world = getWorldForLevel(levelId);
  const levelInWorld = ((levelId - 1) % 20) + 1;
  const isBoss = levelInWorld === 20;
  const isSpeedGate = levelInWorld === 10 || levelInWorld === 16;
  const diff = Math.min(5, Math.floor((levelInWorld - 1) / 4) + 1) as 1 | 2 | 3 | 4 | 5;

  return {
    id: levelId,
    worldId: world.id,
    levelNumber: levelInWorld,
    title: isBoss ? `${world.boss.name}` : `Realm Level ${levelId}`,
    levelType: isBoss ? "boss" : isSpeedGate ? "speed_gate" : "mixed",
    concepts: ["mental_addition", "mental_multiplication", "fraction_reasoning", "percentage_of_number", "simple_equation", "mental_area"],
    difficulty: diff,
    questionCount: isBoss ? 8 : 5,
    timeLimitSeconds: isBoss ? 75 : 55,
    starThresholds: standardThresholds(0.8, isBoss ? 50 : 35),
    rewardXp: 200 + levelId * 2,
    rewardTokens: isBoss ? 50 : 10,
    isMilestone: isBoss,
    boss: isBoss ? world.boss : undefined,
    description: isBoss ? `Defeat ${world.boss.name} to advance!` : `Traverse level ${levelId} in ${world.name}`,
  };
}
